env:
  browser: true
  es6: true
  webextensions: true

parserOptions:
  ecmaVersion: 2017

extends:
  - eslint:recommended

globals:
  BrowserStorageCredentials: false
  ClassicEditor: false
  Jose: false
  JoseJWE: false
  Kinto: false
  KintoClient: false
  Quill: false
  TestPilotGA: false
  customizeEditor: false
  disconnectFromKinto: false
  formatFooterTime: false
  fxaCryptoRelier: false
  fxaFetchProfile: false
  fxaRenewCredential: false
  getPadStats: false
  loadFromKinto: false
  localizeEditorButtons: false
  migrationCheck: false
  migrationNote: false
  migrationBody: false
  retrieveNote: false
  saveToKinto: false
  setAnimation: false

root: true

rules:
  eqeqeq: error
  linebreak-style: [error, unix]
  no-console: warn
  no-var: error
  prefer-const: error
  quotes: [error, single]
  semi: [error, always]
