env:
  browser: true
  es6: true
  webextensions: true

extends:
  - eslint:recommended

globals:
  KintoClient: false
  Quill: false

root: true

rules:
  eqeqeq: error
  indent: [error, 2]
  linebreak-style: [error, unix]
  no-console: warn
  no-var: error
  prefer-const: error
  quotes: [error, single]
  semi: [error, always]
