version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    scopes:
        - "secrets:get:project/testpilot/notes"
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
          - push
          - release
    payload:
      features:
        taskclusterProxy: true
      maxRunTime: 3600
      image: circleci/android:api-25-node8-alpha
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          cd ~ && git clone {{event.head.repo.url}} repo && cd repo && git config
          advice.detachedHead false && git checkout {{event.head.sha}} && cd native &&
          source ./misc/taskcluster_secrets.sh && echo "exported: ${TOKEN}" && ./misc/download_keystore.sh &&
          npm install . && echo $foo && cd android && ./gradlew assembleRelease -PMYAPP_RELEASE_STORE_FILE=$MYAPP_RELEASE_STORE_FILE -PMYAPP_RELEASE_KEY_ALIAS=$MYAPP_RELEASE_KEY_ALIAS -PMYAPP_RELEASE_STORE_PASSWORD=$MYAPP_RELEASE_STORE_PASSWORD -PMYAPP_RELEASE_KEY_PASSWORD=$MYAPP_RELEASE_KEY_PASSWORD
    metadata:
      name: Test Pilot Notes
      description: Test Pilot Notes
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators
