language: node_js
_aliases:
  - &test
    env: DISPLAY=:99.0
    before_install:
      - sh -e /etc/init.d/xvfb start
      - sleep 5
  - &unit-test
    env: FIREFOX_BINARY=firefox
    addons:
      firefox: latest
    <<: *test
  - &integration-test
    env: MOZ_HEADLESS=1
    addons:
      firefox: latest-nightly
    <<: *test

jobs:
  include:
    - stage:
      node_js: 8
      <<: *unit-test
      script: npm run test:karma
    - stage:
      node_js: 8
      <<: *integration-test
      script: npm run test:ui
    - stage:
      node_js: 8
      script: npm run build
      env: BUILD_NOTES
    - stage:
      node_js: 8
      script: npm run lint
      env: LINT
      before_script: npm run build
      before_install:
