language: node_js
addons:
  firefox: latest
node_js:
  - "6"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run build
  - npm run lint
  - npm run test
env:
  global:
    - FIREFOX_BINARY: firefox
